
//----------------------------------------------------
// The following code was generated by CUP v0.11b 20160615 (GIT 4ac7450)
//----------------------------------------------------

/** CUP generated class containing symbol constants. */
public class sym {
  /* terminals */
  public static final int MOD = 15;
  public static final int AND = 22;
  public static final int CONTINUE = 10;
  public static final int CLASS = 2;
  public static final int OR = 23;
  public static final int INT = 3;
  public static final int PIZ = 26;
  public static final int WHILE = 6;
  public static final int SUMA = 11;
  public static final int NOT = 24;
  public static final int MULTI = 13;
  public static final int PDER = 27;
  public static final int RETURN = 8;
  public static final int LESSEQUALS = 20;
  public static final int ID = 30;
  public static final int NUM = 31;
  public static final int BOOLEAN = 4;
  public static final int NOTEQUALS = 17;
  public static final int EQUALS = 16;
  public static final int LESSTHAN = 18;
  public static final int EOF = 0;
  public static final int BREAK = 9;
  public static final int DIV = 14;
  public static final int MORETHAN = 19;
  public static final int LDER = 29;
  public static final int error = 1;
  public static final int PUNTOCOMA = 25;
  public static final int FOR = 7;
  public static final int VOID = 5;
  public static final int LIZ = 28;
  public static final int MOREEQUALS = 21;
  public static final int RESTA = 12;
  public static final String[] terminalNames = new String[] {
  "EOF",
  "error",
  "CLASS",
  "INT",
  "BOOLEAN",
  "VOID",
  "WHILE",
  "FOR",
  "RETURN",
  "BREAK",
  "CONTINUE",
  "SUMA",
  "RESTA",
  "MULTI",
  "DIV",
  "MOD",
  "EQUALS",
  "NOTEQUALS",
  "LESSTHAN",
  "MORETHAN",
  "LESSEQUALS",
  "MOREEQUALS",
  "AND",
  "OR",
  "NOT",
  "PUNTOCOMA",
  "PIZ",
  "PDER",
  "LIZ",
  "LDER",
  "ID",
  "NUM"
  };
}




